### PR TITLE
Issue Fixed  Related to Delete List Items from auto export Report setting and associated config setting for Cron.

### PR DESCRIPTION
**Pull request by Ravikr139**
Issue Fixed to remove auto export Report list and config setting for Cron.

### CODE REVIEW

**Comment by Ravikr139** [comment]
Issue Fixed to remove auto export Report list and config setting for Cron.
@peterjaap

**Comment by peterjaap** [comment]
@Ravikr139 what issue are we talking about?

**Comment by Ravikr139** [comment]
@peterjaap issue specially related to the deletion of existing automated export settings (Report->Automated Exports).
It was not working there.
This issue has been fixed in this.

**Comment by peterjaap** [comment]
Right, thanks!

**Comment by peterjaap** [comment]
I'm not the maintainer however, so I can't merge this. LGTM however.

@jantzenw @brobie

**Comment by Ravikr139** [comment]
@jantzenw @brobie 

Please Review and merge this PR.
It will fix the major issue related to delete export list setting.

**Comment by jantzenw** [comment]
This PR is being merged. This issue is also fixed in v3.1.1+ (albeit slightly differently). 

Side note, the master branch is out of date. It is purposely not being updated much because this repo lacked tags for many years, causing some users to install the extension as "dev-master", so updates to the master branch could have serious consequences.

**Pull request merged**
